<?php
/**
 * Generated By Command: translation:export
 */

return [
    '对公账户' => '@origin',
    '对私账户' => '@origin',
    'P卡' => '@origin',
    '正在进行' => '@origin',
    '结算中' => '@origin',
    '已结算' => '@origin',
    '已结算（转期初金额）' => '@origin',
    '未知状态' => '@origin',
    '无需冻结' => '@origin',
    '冻结中' => '@origin',
    '已解冻' => '@origin',
];
