<?php
/**
 * Generated By Command: translation:export
 */

return [
    '上门取货' => '@origin',
    '一件代发' => '@origin',
    'N/A' => '@origin',
    '高' => '@origin',
    '中' => '@origin',
    '低' => '@origin',
];
