<?php
/**
 * Generated By Command: translation:export
 */

return [
    '高' => '@origin',
    '中' => '@origin',
    '低' => '@origin',
    '产品质量' => '@origin',
    '交易稳定' => '@origin',
    '服务质量' => '@origin',
    '商家信誉' => '@origin',
];
