<?php
/**
 * Generated By Command: translation:export
 */

return [
    '自动推荐' => '@origin',
    '手工添加' => '@origin',
    '热卖产品在前' => '@origin',
    '新品到货在前' => '@origin',
    '热门下载在前' => '@origin',
    '价格最低在前' => '@origin',
    '价格最低在后' => '@origin',
];
