<?php
// @formatter:off

namespace PHPSTORM_META {

   /**
    * PhpStorm Meta file, to provide autocomplete information for PhpStorm
    * Generated on 2021-07-22 03:05:02.
    *
    * @author Barry vd. Heuvel <barryvdh@gmail.com>
    * @see https://github.com/barryvdh/laravel-ide-helper
    */
    override(\Illuminate\Contracts\Container\Container::make(0), map([
        '' => '@',
        'DebugBar\HttpDriverInterface' => \Framework\Debug\HttpDriver::class,
        'Framework\Contracts\Debug\ExceptionHandler' => \App\Components\Debug\ExceptionHandler::class,
        'Framework\ErrorHandler\ErrorHandlerInterface' => \Framework\ErrorHandler\handlers\WhoopsHandler::class,
        'Illuminate\Contracts\Console\Kernel' => \App\Commands\Kernel::class,
        'barcode' => \App\Components\BarcodeGenerator::class,
        'cache' => \Framework\Cache\Cache::class,
        'cache.manager' => \Framework\Cache\CacheManager::class,
        'cache.psr16' => \Symfony\Component\Cache\Psr16Cache::class,
        'cache.psr6' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'command.ide-helper.meta' => \Framework\IdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Framework\IdeHelper\Console\ModelsCommand::class,
        'console.artisan' => \Illuminate\Console\Application::class,
        'db' => \Illuminate\Database\Capsule\Manager::class,
        'db-aes' => \App\Components\AES\DBAES::class,
        'db.connection' => \Illuminate\Database\MySqlConnection::class,
        'db.manager' => \Illuminate\Database\DatabaseManager::class,
        'debugbar' => \Framework\Debug\DebugBar::class,
        'dompdf' => \App\Components\Pdf\DomPdfGenerator::class,
        'dompdf.instance' => \Dompdf\Dompdf::class,
        'dompdf.options' => \Dompdf\Options::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'log' => \Framework\Log\LogManager::class,
        'mpdf' => \App\Components\Pdf\MPdfGenerator::class,
        'mpdf.instance' => \Mpdf\Mpdf::class,
        'redis' => \Framework\Redis\RedisManager::class,
        'session' => \Framework\Session\Session::class,
        'session.manager' => \Framework\Session\SessionManager::class,
        'sms' => \Overtrue\EasySms\EasySms::class,
        'storage.manager' => \Framework\Storage\StorageManager::class,
        'translator' => \Framework\Translation\Translator::class,
        'translator.loader' => \Illuminate\Translation\FileLoader::class,
        'validator' => \Illuminate\Validation\Factory::class,
        'view' => \Framework\View\ViewFactory::class,
        'view.aliases' => \Framework\Aliases\Aliases::class,
        'view.asset' => \Framework\View\Assets\AssetManager::class,
        'view.finder' => \Framework\View\ViewFinder::class,
        'view.renderer.php' => \Framework\View\PhpRenderer::class,
        'view.renderer.twig' => \Framework\View\TwigRenderer::class,
        'app' => \Framework\Foundation\Application::class,
        'ocRegistry' => \Registry::class,
        'ocConfig' => \Framework\Config\Config::class,
        'request' => \Framework\Http\Request::class,
        'Illuminate\Contracts\Container\Container' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Foundation\Application' => \Framework\Foundation\Application::class,
        'Psr\Container\ContainerInterface' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Events\Dispatcher' => \Illuminate\Events\Dispatcher::class,
        'Psr\Log\LoggerInterface' => \Framework\Log\LogManager::class,
        'Illuminate\Database\Connection' => \Illuminate\Database\MySqlConnection::class,
        'Illuminate\Database\ConnectionInterface' => \Illuminate\Database\MySqlConnection::class,
        'registry' => \Registry::class,
        'Framework\Http\Session' => \Framework\Session\Session::class,
        'Framework\View\ViewFinderInterface' => \Framework\View\ViewFinder::class,
        'console' => \App\Commands\Kernel::class,
        'Framework\Foundation\Console\Kernel' => \App\Commands\Kernel::class,
        'Psr\Cache\CacheItemInterface' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'Psr\SimpleCache\CacheInterface' => \Symfony\Component\Cache\Psr16Cache::class,
        'Illuminate\Contracts\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Contracts\Translation\Loader' => \Illuminate\Translation\FileLoader::class,
        'Illuminate\Contracts\Validation\Factory' => \Illuminate\Validation\Factory::class,
    ]));
    override(\Illuminate\Contracts\Container\Container::makeWith(0), map([
        '' => '@',
        'DebugBar\HttpDriverInterface' => \Framework\Debug\HttpDriver::class,
        'Framework\Contracts\Debug\ExceptionHandler' => \App\Components\Debug\ExceptionHandler::class,
        'Framework\ErrorHandler\ErrorHandlerInterface' => \Framework\ErrorHandler\handlers\WhoopsHandler::class,
        'Illuminate\Contracts\Console\Kernel' => \App\Commands\Kernel::class,
        'barcode' => \App\Components\BarcodeGenerator::class,
        'cache' => \Framework\Cache\Cache::class,
        'cache.manager' => \Framework\Cache\CacheManager::class,
        'cache.psr16' => \Symfony\Component\Cache\Psr16Cache::class,
        'cache.psr6' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'command.ide-helper.meta' => \Framework\IdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Framework\IdeHelper\Console\ModelsCommand::class,
        'console.artisan' => \Illuminate\Console\Application::class,
        'db' => \Illuminate\Database\Capsule\Manager::class,
        'db-aes' => \App\Components\AES\DBAES::class,
        'db.connection' => \Illuminate\Database\MySqlConnection::class,
        'db.manager' => \Illuminate\Database\DatabaseManager::class,
        'debugbar' => \Framework\Debug\DebugBar::class,
        'dompdf' => \App\Components\Pdf\DomPdfGenerator::class,
        'dompdf.instance' => \Dompdf\Dompdf::class,
        'dompdf.options' => \Dompdf\Options::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'log' => \Framework\Log\LogManager::class,
        'mpdf' => \App\Components\Pdf\MPdfGenerator::class,
        'mpdf.instance' => \Mpdf\Mpdf::class,
        'redis' => \Framework\Redis\RedisManager::class,
        'session' => \Framework\Session\Session::class,
        'session.manager' => \Framework\Session\SessionManager::class,
        'sms' => \Overtrue\EasySms\EasySms::class,
        'storage.manager' => \Framework\Storage\StorageManager::class,
        'translator' => \Framework\Translation\Translator::class,
        'translator.loader' => \Illuminate\Translation\FileLoader::class,
        'validator' => \Illuminate\Validation\Factory::class,
        'view' => \Framework\View\ViewFactory::class,
        'view.aliases' => \Framework\Aliases\Aliases::class,
        'view.asset' => \Framework\View\Assets\AssetManager::class,
        'view.finder' => \Framework\View\ViewFinder::class,
        'view.renderer.php' => \Framework\View\PhpRenderer::class,
        'view.renderer.twig' => \Framework\View\TwigRenderer::class,
        'app' => \Framework\Foundation\Application::class,
        'ocRegistry' => \Registry::class,
        'ocConfig' => \Framework\Config\Config::class,
        'request' => \Framework\Http\Request::class,
        'Illuminate\Contracts\Container\Container' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Foundation\Application' => \Framework\Foundation\Application::class,
        'Psr\Container\ContainerInterface' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Events\Dispatcher' => \Illuminate\Events\Dispatcher::class,
        'Psr\Log\LoggerInterface' => \Framework\Log\LogManager::class,
        'Illuminate\Database\Connection' => \Illuminate\Database\MySqlConnection::class,
        'Illuminate\Database\ConnectionInterface' => \Illuminate\Database\MySqlConnection::class,
        'registry' => \Registry::class,
        'Framework\Http\Session' => \Framework\Session\Session::class,
        'Framework\View\ViewFinderInterface' => \Framework\View\ViewFinder::class,
        'console' => \App\Commands\Kernel::class,
        'Framework\Foundation\Console\Kernel' => \App\Commands\Kernel::class,
        'Psr\Cache\CacheItemInterface' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'Psr\SimpleCache\CacheInterface' => \Symfony\Component\Cache\Psr16Cache::class,
        'Illuminate\Contracts\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Contracts\Translation\Loader' => \Illuminate\Translation\FileLoader::class,
        'Illuminate\Contracts\Validation\Factory' => \Illuminate\Validation\Factory::class,
    ]));
    override(\Framework\Foundation\Application::get(0), map([
        '' => '@',
        'DebugBar\HttpDriverInterface' => \Framework\Debug\HttpDriver::class,
        'Framework\Contracts\Debug\ExceptionHandler' => \App\Components\Debug\ExceptionHandler::class,
        'Framework\ErrorHandler\ErrorHandlerInterface' => \Framework\ErrorHandler\handlers\WhoopsHandler::class,
        'Illuminate\Contracts\Console\Kernel' => \App\Commands\Kernel::class,
        'barcode' => \App\Components\BarcodeGenerator::class,
        'cache' => \Framework\Cache\Cache::class,
        'cache.manager' => \Framework\Cache\CacheManager::class,
        'cache.psr16' => \Symfony\Component\Cache\Psr16Cache::class,
        'cache.psr6' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'command.ide-helper.meta' => \Framework\IdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Framework\IdeHelper\Console\ModelsCommand::class,
        'console.artisan' => \Illuminate\Console\Application::class,
        'db' => \Illuminate\Database\Capsule\Manager::class,
        'db-aes' => \App\Components\AES\DBAES::class,
        'db.connection' => \Illuminate\Database\MySqlConnection::class,
        'db.manager' => \Illuminate\Database\DatabaseManager::class,
        'debugbar' => \Framework\Debug\DebugBar::class,
        'dompdf' => \App\Components\Pdf\DomPdfGenerator::class,
        'dompdf.instance' => \Dompdf\Dompdf::class,
        'dompdf.options' => \Dompdf\Options::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'log' => \Framework\Log\LogManager::class,
        'mpdf' => \App\Components\Pdf\MPdfGenerator::class,
        'mpdf.instance' => \Mpdf\Mpdf::class,
        'redis' => \Framework\Redis\RedisManager::class,
        'session' => \Framework\Session\Session::class,
        'session.manager' => \Framework\Session\SessionManager::class,
        'sms' => \Overtrue\EasySms\EasySms::class,
        'storage.manager' => \Framework\Storage\StorageManager::class,
        'translator' => \Framework\Translation\Translator::class,
        'translator.loader' => \Illuminate\Translation\FileLoader::class,
        'validator' => \Illuminate\Validation\Factory::class,
        'view' => \Framework\View\ViewFactory::class,
        'view.aliases' => \Framework\Aliases\Aliases::class,
        'view.asset' => \Framework\View\Assets\AssetManager::class,
        'view.finder' => \Framework\View\ViewFinder::class,
        'view.renderer.php' => \Framework\View\PhpRenderer::class,
        'view.renderer.twig' => \Framework\View\TwigRenderer::class,
        'app' => \Framework\Foundation\Application::class,
        'ocRegistry' => \Registry::class,
        'ocConfig' => \Framework\Config\Config::class,
        'request' => \Framework\Http\Request::class,
        'Illuminate\Contracts\Container\Container' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Foundation\Application' => \Framework\Foundation\Application::class,
        'Psr\Container\ContainerInterface' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Events\Dispatcher' => \Illuminate\Events\Dispatcher::class,
        'Psr\Log\LoggerInterface' => \Framework\Log\LogManager::class,
        'Illuminate\Database\Connection' => \Illuminate\Database\MySqlConnection::class,
        'Illuminate\Database\ConnectionInterface' => \Illuminate\Database\MySqlConnection::class,
        'registry' => \Registry::class,
        'Framework\Http\Session' => \Framework\Session\Session::class,
        'Framework\View\ViewFinderInterface' => \Framework\View\ViewFinder::class,
        'console' => \App\Commands\Kernel::class,
        'Framework\Foundation\Console\Kernel' => \App\Commands\Kernel::class,
        'Psr\Cache\CacheItemInterface' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'Psr\SimpleCache\CacheInterface' => \Symfony\Component\Cache\Psr16Cache::class,
        'Illuminate\Contracts\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Contracts\Translation\Loader' => \Illuminate\Translation\FileLoader::class,
        'Illuminate\Contracts\Validation\Factory' => \Illuminate\Validation\Factory::class,
    ]));
    override(\app(0), map([
        '' => '@',
        'DebugBar\HttpDriverInterface' => \Framework\Debug\HttpDriver::class,
        'Framework\Contracts\Debug\ExceptionHandler' => \App\Components\Debug\ExceptionHandler::class,
        'Framework\ErrorHandler\ErrorHandlerInterface' => \Framework\ErrorHandler\handlers\WhoopsHandler::class,
        'Illuminate\Contracts\Console\Kernel' => \App\Commands\Kernel::class,
        'barcode' => \App\Components\BarcodeGenerator::class,
        'cache' => \Framework\Cache\Cache::class,
        'cache.manager' => \Framework\Cache\CacheManager::class,
        'cache.psr16' => \Symfony\Component\Cache\Psr16Cache::class,
        'cache.psr6' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'command.ide-helper.meta' => \Framework\IdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Framework\IdeHelper\Console\ModelsCommand::class,
        'console.artisan' => \Illuminate\Console\Application::class,
        'db' => \Illuminate\Database\Capsule\Manager::class,
        'db-aes' => \App\Components\AES\DBAES::class,
        'db.connection' => \Illuminate\Database\MySqlConnection::class,
        'db.manager' => \Illuminate\Database\DatabaseManager::class,
        'debugbar' => \Framework\Debug\DebugBar::class,
        'dompdf' => \App\Components\Pdf\DomPdfGenerator::class,
        'dompdf.instance' => \Dompdf\Dompdf::class,
        'dompdf.options' => \Dompdf\Options::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'log' => \Framework\Log\LogManager::class,
        'mpdf' => \App\Components\Pdf\MPdfGenerator::class,
        'mpdf.instance' => \Mpdf\Mpdf::class,
        'redis' => \Framework\Redis\RedisManager::class,
        'session' => \Framework\Session\Session::class,
        'session.manager' => \Framework\Session\SessionManager::class,
        'sms' => \Overtrue\EasySms\EasySms::class,
        'storage.manager' => \Framework\Storage\StorageManager::class,
        'translator' => \Framework\Translation\Translator::class,
        'translator.loader' => \Illuminate\Translation\FileLoader::class,
        'validator' => \Illuminate\Validation\Factory::class,
        'view' => \Framework\View\ViewFactory::class,
        'view.aliases' => \Framework\Aliases\Aliases::class,
        'view.asset' => \Framework\View\Assets\AssetManager::class,
        'view.finder' => \Framework\View\ViewFinder::class,
        'view.renderer.php' => \Framework\View\PhpRenderer::class,
        'view.renderer.twig' => \Framework\View\TwigRenderer::class,
        'app' => \Framework\Foundation\Application::class,
        'ocRegistry' => \Registry::class,
        'ocConfig' => \Framework\Config\Config::class,
        'request' => \Framework\Http\Request::class,
        'Illuminate\Contracts\Container\Container' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Foundation\Application' => \Framework\Foundation\Application::class,
        'Psr\Container\ContainerInterface' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Events\Dispatcher' => \Illuminate\Events\Dispatcher::class,
        'Psr\Log\LoggerInterface' => \Framework\Log\LogManager::class,
        'Illuminate\Database\Connection' => \Illuminate\Database\MySqlConnection::class,
        'Illuminate\Database\ConnectionInterface' => \Illuminate\Database\MySqlConnection::class,
        'registry' => \Registry::class,
        'Framework\Http\Session' => \Framework\Session\Session::class,
        'Framework\View\ViewFinderInterface' => \Framework\View\ViewFinder::class,
        'console' => \App\Commands\Kernel::class,
        'Framework\Foundation\Console\Kernel' => \App\Commands\Kernel::class,
        'Psr\Cache\CacheItemInterface' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'Psr\SimpleCache\CacheInterface' => \Symfony\Component\Cache\Psr16Cache::class,
        'Illuminate\Contracts\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Contracts\Translation\Loader' => \Illuminate\Translation\FileLoader::class,
        'Illuminate\Contracts\Validation\Factory' => \Illuminate\Validation\Factory::class,
    ]));
    override(\resolve(0), map([
        '' => '@',
        'DebugBar\HttpDriverInterface' => \Framework\Debug\HttpDriver::class,
        'Framework\Contracts\Debug\ExceptionHandler' => \App\Components\Debug\ExceptionHandler::class,
        'Framework\ErrorHandler\ErrorHandlerInterface' => \Framework\ErrorHandler\handlers\WhoopsHandler::class,
        'Illuminate\Contracts\Console\Kernel' => \App\Commands\Kernel::class,
        'barcode' => \App\Components\BarcodeGenerator::class,
        'cache' => \Framework\Cache\Cache::class,
        'cache.manager' => \Framework\Cache\CacheManager::class,
        'cache.psr16' => \Symfony\Component\Cache\Psr16Cache::class,
        'cache.psr6' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'command.ide-helper.meta' => \Framework\IdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Framework\IdeHelper\Console\ModelsCommand::class,
        'console.artisan' => \Illuminate\Console\Application::class,
        'db' => \Illuminate\Database\Capsule\Manager::class,
        'db-aes' => \App\Components\AES\DBAES::class,
        'db.connection' => \Illuminate\Database\MySqlConnection::class,
        'db.manager' => \Illuminate\Database\DatabaseManager::class,
        'debugbar' => \Framework\Debug\DebugBar::class,
        'dompdf' => \App\Components\Pdf\DomPdfGenerator::class,
        'dompdf.instance' => \Dompdf\Dompdf::class,
        'dompdf.options' => \Dompdf\Options::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'log' => \Framework\Log\LogManager::class,
        'mpdf' => \App\Components\Pdf\MPdfGenerator::class,
        'mpdf.instance' => \Mpdf\Mpdf::class,
        'redis' => \Framework\Redis\RedisManager::class,
        'session' => \Framework\Session\Session::class,
        'session.manager' => \Framework\Session\SessionManager::class,
        'sms' => \Overtrue\EasySms\EasySms::class,
        'storage.manager' => \Framework\Storage\StorageManager::class,
        'translator' => \Framework\Translation\Translator::class,
        'translator.loader' => \Illuminate\Translation\FileLoader::class,
        'validator' => \Illuminate\Validation\Factory::class,
        'view' => \Framework\View\ViewFactory::class,
        'view.aliases' => \Framework\Aliases\Aliases::class,
        'view.asset' => \Framework\View\Assets\AssetManager::class,
        'view.finder' => \Framework\View\ViewFinder::class,
        'view.renderer.php' => \Framework\View\PhpRenderer::class,
        'view.renderer.twig' => \Framework\View\TwigRenderer::class,
        'app' => \Framework\Foundation\Application::class,
        'ocRegistry' => \Registry::class,
        'ocConfig' => \Framework\Config\Config::class,
        'request' => \Framework\Http\Request::class,
        'Illuminate\Contracts\Container\Container' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Foundation\Application' => \Framework\Foundation\Application::class,
        'Psr\Container\ContainerInterface' => \Framework\Foundation\Application::class,
        'Illuminate\Contracts\Events\Dispatcher' => \Illuminate\Events\Dispatcher::class,
        'Psr\Log\LoggerInterface' => \Framework\Log\LogManager::class,
        'Illuminate\Database\Connection' => \Illuminate\Database\MySqlConnection::class,
        'Illuminate\Database\ConnectionInterface' => \Illuminate\Database\MySqlConnection::class,
        'registry' => \Registry::class,
        'Framework\Http\Session' => \Framework\Session\Session::class,
        'Framework\View\ViewFinderInterface' => \Framework\View\ViewFinder::class,
        'console' => \App\Commands\Kernel::class,
        'Framework\Foundation\Console\Kernel' => \App\Commands\Kernel::class,
        'Psr\Cache\CacheItemInterface' => \Symfony\Component\Cache\Adapter\RedisAdapter::class,
        'Psr\SimpleCache\CacheInterface' => \Symfony\Component\Cache\Psr16Cache::class,
        'Illuminate\Contracts\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Translation\Translator' => \Framework\Translation\Translator::class,
        'Illuminate\Contracts\Translation\Loader' => \Illuminate\Translation\FileLoader::class,
        'Illuminate\Contracts\Validation\Factory' => \Illuminate\Validation\Factory::class,
    ]));


    override(\Illuminate\Support\Arr::add(0), type(0));
    override(\Illuminate\Support\Arr::except(0), type(0));
    override(\Illuminate\Support\Arr::first(0), elementType(0));
    override(\Illuminate\Support\Arr::last(0), elementType(0));
    override(\Illuminate\Support\Arr::get(0), elementType(0));
    override(\Illuminate\Support\Arr::only(0), type(0));
    override(\Illuminate\Support\Arr::prepend(0), type(0));
    override(\Illuminate\Support\Arr::pull(0), elementType(0));
    override(\Illuminate\Support\Arr::set(0), type(0));
    override(\Illuminate\Support\Arr::shuffle(0), type(0));
    override(\Illuminate\Support\Arr::sort(0), type(0));
    override(\Illuminate\Support\Arr::sortRecursive(0), type(0));
    override(\Illuminate\Support\Arr::where(0), type(0));
    override(\array_add(0), type(0));
    override(\array_except(0), type(0));
    override(\array_first(0), elementType(0));
    override(\array_last(0), elementType(0));
    override(\array_get(0), elementType(0));
    override(\array_only(0), type(0));
    override(\array_prepend(0), type(0));
    override(\array_pull(0), elementType(0));
    override(\array_set(0), type(0));
    override(\array_sort(0), type(0));
    override(\array_sort_recursive(0), type(0));
    override(\array_where(0), type(0));
    override(\head(0), elementType(0));
    override(\last(0), elementType(0));
    override(\with(0), type(0));
    override(\tap(0), type(0));

}
