<?php
/**
 * Generated By Command: translation:export
 */

return [
    '该手机号与当前绑定的号码相同' => 'This phone number is the same as the number currently bound to the account.',
    '非正常操作，请刷新页面后重试' => 'Abnormal operation. Please refresh the page and try again later.',
    '该手机号已被其他账号绑定' => 'This phone number has already been bound to another account.',
    '短信发送次数过多，请1小时后重试' => 'The verification message has been sent too many times. Please try again in one hour.',
    '验证码发送失败，请重试' => 'Failed to send the verification code to your phone, please try again.',
    '验证码错误' => 'The verification code is wrong.',
    '手机号格式不正确，请重新输入' => 'Incorrect phone number format, please enter again.',
];
