<?php
/**
 * Generated By Command: translation:export
 */

return [
    '盘亏管理' => '@origin',
    '批次号' => '@origin',
    '处理状态' => '@origin',
    '凭证' => '@origin',
    '文件名' => '@origin',
    '大小' => '@origin',
    '状态' => '@origin',
    '操作' => '@origin',
    '备注' => '@origin',
    '盘亏库存明细' => '@origin',
    '序号' => '@origin',
    'Item Code' => '@origin',
    'MPN' => '@origin',
    '数量' => '@origin',
    'Seller申报金额/件' => '@origin',
    'Seller申报金额（Item合计）' => '@origin',
    'Seller申报资料' => '@origin',
];
