<?php
/**
 * Generated By Command: translation:export
 */

return [
    '填写基础信息' => 'Basic Information',
    '运输方式' => 'Shipping Method',
    '运输方式不能为空' => 'Shipping Method cannot be empty.',
    '集装箱尺寸' => 'Container Size',
    '集装箱尺寸不能为空' => 'Container Size cannot be empty.',
    '起运港' => 'Originating Port',
    '起运港不能为空' => 'Originating Port cannot be empty.',
    '起运城市' => 'Originating City',
    '起运城市不能为空' => 'Originating City cannot be empty.',
    '期望船期' => 'Requested Shipping Date',
    '期望船期不能为空' => 'Requested Shipping Date cannot be empty.',
    '期望发货时间' => 'Requested Shipping Date',
    '期望发货时间不能为空' => 'Requested Shipping Date cannot be empty.',
    '下载入库单模板' => 'Download Incoming Shipment Template',
    '下载模板' => 'Download Template',
    '选择入库单文件并上传' => 'Upload Incoming Shipment',
    '点击上传' => 'Click to upload',
    '确认上传数据' => 'Confirm Uploaded Information',
    '点击<strong>提交</strong>确认提交申请，点击<strong>保存</strong>仅保存入库单，点击<strong>取消</strong>则取消操作' => 'Click on <strong>\'Submit\'</strong> to confirm the submission,  '."\r\n"
        .'Click on <strong>\'Save\'</strong> to save the Incoming Shipment and submit it later, Click on <strong>\'Cancel\'</strong> to cancel the operation.',
    '取消' => 'Cancel',
    '保存' => 'Save',
    '提交' => 'Submit',
    '上传文件格式只能为xls或者xlsx文件' => 'Upload files in .xls / .xlsx format only',
    '请选择文件' => 'Please select a file',
    '确认提交？' => 'Do you confirm to submit this incoming shipment?',
    '入库单导入' => 'Import Incoming Shipment',
    '注意' => 'Attention',
    '确认' => 'Confirm',
    'yes' => 'Yes',
    'no' => 'No',
    'ok' => 'Ok',
    '文件错误!' => 'File error!',
    '文件为空，请重新上传！' => 'The file is empty, please upload again!',
    '你确认提交这个入库单吗？' => 'Do you confirm to submit this incoming shipment?',
    '填写托书' => 'Fill in the Shipping Order Book',
    '请填写托书' => 'Please fill in the shipping order book',
];
