<?php
/**
 * Generated By Command: translation:export
 */

return [
    '文件夹移动失败，目前只支持3层文件目录' => 'The folder moving is failed. The catalog that the folder is moved in cannot be under a tertiary level.',
    '文件夹名称不规范' => 'The folder name does not meet the requirements.',
    '上传文件不合法' => 'File format error',
    '单个图片文件大小不超过20M，其他文件不能超过50M' => 'The single image size should not be larger than 20M, and other files not larger than 50M.',
    '文件格式仅限图片jpeg/jpg/png/gif 或者文档doc(x)/xls(x)/ppt(x)/pdf/txt' => 'The file only supports images in .jpeg/.jpg/.png/.gif format or documents in .doc(x)/.xl(s)/.ppt(x)/.txt format.',
    '同一文件夹下，文件名称不能重复' => 'The file name cannot be a duplicate under the same folder.',
    '文件夹名称不能重复' => 'The folder name cannot be a duplicate.',
    '文件名称不规范' => 'The file name does not meet the requirements.',
    '文件重命名成功' => 'Successfully Renamed',
    '文件移动成功' => 'Successfully Moved',
    '文件删除成功' => 'Successfully Deleted',
    '不能将文件夹移动到自身或者其子目录下' => 'The folder cannot be moved to its original catalog or subcatalog.',
    '部分文件已存在,移动失败' => 'Some of the files cannot be moved since they have already existed.',
    '文件名称只能包含数字、中英文、空格、（）- 或者 _' => 'The file name can only contain digits, Chinese characters, English letters, spaces, \'( )\', \'-\' or \'_\'.',
    '文件名称不能超过100字符' => 'The file name shall be limited to 100 characters.',
    '文件名称只能以中英文或者数字开头' => 'The file name can only start with a Chinese characters, English letters or a digit.',
    '文件不存在' => 'File does not exist.',
];
