<?php
/**
 * Generated By Command: translation:export
 */

return [
    '产品运费计算失败，若要更新产品尺寸，请联系客服。' => 'Fulfillment fee calculation failed. If you want to update the dimension , please contact Customer Service.',
];
