<?php
/**
 * Generated By Command: translation:export
 */

return [
    '系统繁忙，请稍后在试' => 'The system is busy, please try again later.',
    'No.' => '@origin',
    'Item Code' => '@origin',
    'MPN' => '@origin',
    '产品名称' => 'Product Name',
    '入库类型' => 'Receiving Type',
    '仓库收货数量' => 'Warehouse Receiving Qty',
    '当前在库数' => 'Current In-stock Qty',
    '入库天数' => 'Days in Stock',
    '批次号' => 'Batch ID',
    '备注' => 'Comment',
    '批次生成日期' => 'Batch Create Date',
    '入库日期' => 'Receiving Date',
    '无效的入出库分类' => 'Invalid inbound and outbound classification.',
    '无效的入出库类型' => 'Invalid entry and exit type.',
    '入库' => 'Warehouse Inbound',
    '出库' => 'Warehouse Outbound',
    '无效的筛选时间' => 'Invalid filter time.',
    '无效的入库类型' => 'Invalid storage type.',
    '入库/出库' => 'Warehouse Inbound/Outbound',
    '类型' => 'Type',
    '数量' => 'Quantity',
    '生成日期' => 'Create Date',
    '提交成功' => 'Successfully',
    '生成日期_1' => 'Batch Create Date',
];
