<?php
/**
 * Generated By Command: translation:export
 */

return [
    '请输入站内链接！' => 'Please enter a site internal URL',
    '所选产品:sku，未在:category分类中，请移除这些产品！' => '{1}The selected product :sku is not in the :category category. Please delete this product.|[2,*]The selected products :sku are not in the :category category. Please delete these products.',
    '产品:sku已失效，请移除这些产品！' => '{1}The product :sku is invalid. Please delete this product.|[2,*]The products :sku are invalid. Please delete these products.',
    '产品:sku返点合约已失效，请移除这些产品！' => '{1}The rebate contract of product :sku is invalid. Please delete this product.|[2,*]The rebate template of products :sku are invalid. Please delete these products.',
    '产品:sku期货合约已失效，请移除这些产品！' => '{1}The future goods contract of product :sku is invalid. Please delete this product.|[2,*]The future goods contract of products :sku are invalid. Please delete these products.',
    '产品:sku现货合约已失效，请移除这些产品！' => '{1}The margin contract of product :sku is invalid. Please delete this product.|[2,*]The margin contract of products :sku are invalid. Please delete these products.',
    '产品:sku已下架，请移除这些产品！' => '{1}The product :sku has been unavailable, please delete it.|[2,*]The products :sku have been unavailable, please delete them.',
    '这个当前页面无模块，请先添加模块' => 'No modules are set for this page. Please add a module first.',
];
