<?php
/**
 * Generated By Command: translation:export
 */

return [
    '修改手机号' => 'Modify Phone Number',
    '验证手机号' => 'Phone Number Verification',
    '完成' => 'Complete',
    '手机号码' => 'Phone Number',
    '验证码' => 'Verification Code',
    '点此获取' => 'Send',
    '没有收到短信验证码？' => 'No verification code received?',
    '1、网络通讯异常可能会造成短信丢失，请重新获取或稍后再试。' => '1. Abnormal network may cause SMS loss, please send the code again or try again later.',
    '2、请核实手机是否已欠费停机，或者屏蔽了系统短信。' => '2. Please check whether your mobile phone has been shut down due to insufficient balance or has blocked the system’s SMS.',
    '3、您也可以尝试将SIM卡移动到另一部手机，然后重试。' => '3. You can also try to move the SIM card to another phone and try again.',
    '确定' => 'Confirm',
    '添加成功，您的手机号码为<span id="savedNumber"></span>' => 'The phone number <span id="savedNumber"></span> is added successfully.',
    '此手机号可作为安全验证的方式用于找回密码、修改手机号等场景，但不能作为登录名使用。' => 'This number can be used as a security verification option to retrieve passwords, modify phone numbers, and other scenarios, but cannot be used as a login name.',
    '账号设置' => 'Account Settings',
    '验证码已发送到你的手机，5分钟内输入有效，请不要轻易告知他人' => 'The verification code has been sent to your phone and it is valid within 5 minutes. Please do not  tell others the verification code.',
    '手机号码是11位数字，请重新输入' => 'The phone number should be 11 digits. Please enter again.',
    '修改成功，您的手机号码为<span id="savedNumber"></span>' => 'The phone number <span id="savedNumber"></span> is modified successfully.',
    '<span id="returnTime">3</span>s后返回<a class="link underline" id="redirect-home" href=":url">:page</a>' => 'Returns to the <a class="link underline" id="redirect-home" href=":url">:page</a> after <span id="returnTime">3</span>s',
    'Seller Central页面' => 'Seller Central',
    '首页' => 'homepage',
    '验证手机号step' => 'Verify',
    '修改手机号step' => 'Modify',
    '手机验证码验证账户 <span class="text-danger">:email</span>，为确认是你本人操作，请完成以下验证' => 'To verify the account <span class="text-danger">:email</span> via phone number, please complete the following verification steps to confirm it is operated by yourself',
    '国家/ 编码' => 'Country/Region',
];
