<?php
/**
 * Generated By Command: translation:export
 */

return [
    '进行中' => 'In-Progress',
    '待开启' => 'Not Started',
    '已结束' => 'Expired',
    '当前活动不可编辑' => 'The current promotion event cannot be edited',
    '请输入活动名称' => 'Please enter the event name',
    '活动名称不能超过200字' => 'The Event Name is limited to 200 characters.',
    '开始时间不可早于当前时间' => 'Start Time must be later than the current time.',
    '开始时间必须要小于结束时间' => 'Start Time must be earlier than End Time',
    '提交成功' => 'Successfully submitted',
    '当前活动不可删除' => 'The current discount details cannot be deleted.',
    '删除成功' => 'Deleted successfully',
    '删除失败' => 'Deleted Failed',
];
