<?php
/**
 * Generated By Command: translation:export
 */

return [
    '进行中' => 'In-Progress',
    '待开启' => 'Not Started',
    '已结束' => 'Expired',
    '已停止' => 'Stopped',
    '提交成功' => 'Successfully submitted',
    '请输入活动名称' => 'Please enter the event name',
    '活动名称不能超过200字' => 'The Event Name is limited to 200 characters.',
    '开始时间不可早于当前时间' => 'Start Time must be later than the current time.',
    '开始时间必须要小于结束时间' => 'Start Time must be earlier than End Time',
    '活动时间与已有活动时间冲突' => 'The promotion duration conflicts with that of the already created promotion.',
    '当前活动不可编辑' => 'The current promotion event cannot be edited',
    '交易方式错误' => 'Wrong transaction type that is not applicable to the promotion',
    '请至少选择一个产品' => 'Please select at least one product',
    '产品数量不可超过40个' => 'The product quantity set for the promotion cannot exceed 40',
    '产品:skus已失效，请移除' => ':skus are invalid, please remove them',
    '产品:skus活动库存超出当前上架库存，请重新设置' => 'The promotional inventory set for :skus exceeds the available quantity, please set again.',
    '操作失败，请重试' => 'Failed to stop the promotion event, please try again',
    '操作成功' => 'Successfully stopped',
    '操作失败，请重试2' => 'Failed to submit the promotion event, please try again',
    '暂无权限' => 'No permission',
    '当前活动不存在' => 'The current promotional event does not exist',
    '补充活动库存失败' => 'Failed to replenish the promotional inventory',
    ':skus等产品库存不足，无法补充库存' => 'The inventory of :skus is insufficient and cannot be replenished.',
    ':skus产品库存不足，无法补充库存' => 'The inventory of :skus is insufficient and cannot be replenished.',
];
