<?php
/**
 * Generated By Command: translation:export
 */

return [
    '个人中心' => '@origin',
    '主页' => '@origin',
    '我的店铺' => '@origin',
    '帮助中心' => '@origin',
    '计算器' => '@origin',
    '账户设置' => '@origin',
    '退出' => '@origin',
];
