<?php
/**
 * Generated By Command: translation:export
 */

return [
    '文件不能上传！' => '@origin',
    '错误的文件格式！' => '@origin',
    '上传的Excel文件内容不正确或数据行为空。' => '@origin',
    '文件为空，请重新上传！' => '@origin',
    'error_upload_code' => implode('|', [
        '未知错误 :count',
        '{1} 警告：上传的文件超过了php.ini中的upload_max_filesize指令！',
        '{2} 警告：上传的文件超出了HTML表单中指定的MAX_FILE_SIZE指令！',
        '{3} 警告：上传的文件仅部分上传！',
        '{4} 警告：没有文件上传！',
        '{6} 警告：缺少一个临时文件夹！',
        '{7} 警告：无法将文件写入磁盘！',
        '{8} 警告：文件扩展名已停止！',
        '{999} 警告：没有错误代码！',
    ]),
    '文件名' => '@origin',
];
