<?php
/**
 * Generated By Command: translation:export
 */

return [
    '首页' => 'Home',
    'Buyer推荐' => 'Recommended Buyer',
    '个人中心' => 'Seller Central',
    '产品管理' => 'Product Management',
    '产品列表' => 'Product List',
    '上传产品' => 'Import Products',
    '历史记录' => 'Upload History',
    '添加产品' => 'Add Product',
    '编辑产品' => 'Edit Product',
    '产品详情(单)' => 'Product Detail',
    '账单管理' => 'Billing Management',
    '结算明细' => 'Settlement Details',
    '结算列表' => 'Settlement Management',
    '结算总单' => 'Settlement Summary',
    '资产管理' => 'Assets Management',
    '盘亏管理' => 'Count Loss Management',
    '库存管理' => 'Inventory Management',
    '批次库存查询' => 'Inventory Query in Batch',
    '入出库查询' => 'Inbound/Outbound Query',
    '入库管理' => 'Incoming Shipment Management',
    '入库单申请' => 'Apply Incoming Shipment',
    '入库单详情' => 'Incoming Shipment Detail',
    '编辑入库单' => 'Edit Incoming Shipment',
    '入库单列表' => 'Incoming Shipment List',
    '店铺首页设计' => 'Store Home Design',
    '店铺介绍页设计' => 'Store Profile Design',
    '店铺管理' => 'Store Management',
    '文件管理' => '@origin',
    'Account Management' => '@origin',
    'Price Ratio Setting' => '@origin',
    'Product Management' => '@origin',
    '产品详情' => '@origin',
];
