<?php
/**
 * Generated By Command: translation:export
 */

return [
    'Label打印' => 'Product Label Print',
    '入库单号' => 'Incoming Shipment ID',
    '打印' => 'Print',
    '筛选' => 'Filter',
    '请输入入库单号或者Item Code/MPN获取打印列表' => 'Please enter the Incoming Shipment ID or Item Code/MPN to generate the labels.',
    '无数据' => 'No Records!',
    '格式错误，请检查打印数量！' => 'Error format！Please check the Print Quantity!',
    '请输入至少一个查询条件！' => 'Please enter a query condition at least!',
    '请最少选择一条记录' => 'Please select a record at least!',
    '预估数量' => 'Estimated Receiving Quantity',
    '预计入库数量' => 'Estimated Receiving Quantity',
    '打印数量' => 'Print Quantity',
    '格式错误，请检查数量！' => 'Error format! Please check the Quantity!',
    '格式错误，请检查预计入库数量！' => 'Error format! Please check the Estimated Receiving Quantity!',
    '加载中，请稍等' => 'Loading, please wait.',
];
