<?php
/**
 * Generated By Command: translation:export
 */

return [
    '该手机号与当前绑定的号码相同' => '@origin',
    '非正常操作，请刷新页面后重试' => '@origin',
    '该手机号已被其他账号绑定' => '@origin',
    '短信发送次数过多，请1小时后重试' => '@origin',
    '验证码发送失败，请重试' => '@origin',
    '验证码错误' => '@origin',
    '手机号格式不正确，请重新输入' => '@origin',
];
