<?php
/**
 * Generated By Command: translation:export
 */

return [
    '上传文件中的upload Id为非法数据' => '@origin',
    '云送仓导单无此产品信息' => '@origin',
    'Line :row :云送仓批量导单校验体积失败' => 'Line :row :The minimum volume requirement of ' . CLOUD_LOGISTICS_VOLUME_LOWER . 'ft³ has not been reached.',
    ':recipient,:phone,:address :原云送仓尺寸报错提醒' => ':recipient,:phone,:address :The minimum volume requirement of ' . CLOUD_LOGISTICS_VOLUME_LOWER . 'ft³ has not been reached.',
    'Line :row :平台无可购买的库存数量，请检查下您的需求是否可调整' => 'Line :row :No inventory is available for purchase. Please check your requirements and decide whether or not to adjust it accordingly.',
];
