<?php
/**
 * Generated By Command: translation:export
 */

return [
    '第:line行，MPN不能为空！' => 'Line :line, MPN can not be empty!',
    '第:line行，更新价格不能为空！' => 'Line :line, Modify Price can not be empty!',
    '第:line行，更新价格格式不正确！' => 'Line :line, Modify Price format is incorrect!',
    '第:line行，MPN与相应产品不匹配！' => 'Line :line, The MPN fields do not match the corresponding product',
    '第:line行，生效时间不能为空！' => 'Line :line, Date of Effect can not be empty!',
    '第:line行，生效时间格式不正确！' => 'Line :line, Date of Effect format is incorrect!',
    '第:line行，生效时间必须晚于当前时间24小时以上！' => 'Line :line, Date of Effect must be more than 24 hours!',
    '第:line行，更新价格只能在:min到:max之间！' => 'Line :line, Modify Price can only be a number between :min and :max!',
    '第:line行，生效时间不能早于当前时间！' => 'Line :line, The effective time cannot be earlier than the current time!',
];
