<?php
/**
 * Generated By Command: translation:export
 */

return [
    'MPN必须大于4且小于30个字符。' => 'MPN must be greater than 4 and less than 30 characters.',
    '失败！MPN不能重复。' => 'Failed!MPN cannot repeat.',
    '产品标题必须大于1且小于200个字符。' => 'Product Title must be greater than 1 and less than 200 characters.',
    '产品尺寸必须大于0且小于80个字符。' => 'Product Size must be greater than 0 and less than 80 characters.',
    '可单独售卖的产品必须设置主图。' => 'Separately sold product main image is needed and must exist.',
    '产品标题不能为空。' => 'Product Title can not be blank.',
    '文档素材为必填项。' => 'The material document field is required when Manual Provided is Yes.',
    '主要颜色不能为空。' => 'Main Color can not be blank.',
    '主要材质不能为空。' => 'Main Material can not be blank.',
    '仅能输入英文和数字' => 'Only English letters and digits are permitted.',
    '失败！MPN不能与已存在的Item Code重复。' => 'Failed! MPN cannot be duplicate with the existing Item Code.',
];
