<?php
/**
 * Generated By Command: translation:export
 */

return [
    'Label打印' => '@origin',
    '入库单号' => '@origin',
    '打印' => '@origin',
    '筛选' => '@origin',
    '请输入入库单号或者Item Code/MPN获取打印列表' => '@origin',
    '无数据' => '@origin',
    '请输入至少一个查询条件！' => '@origin',
    '请最少选择一条记录' => '@origin',
    '预估数量' => '预计入库数量',
    '预计入库数量' => '@origin',
    '打印数量' => '@origin',
    '格式错误，请检查打印数量！' => '@origin',
    '格式错误，请检查数量！' => '@origin',
    '格式错误，请检查预计入库数量！' => '@origin',
    '加载中，请稍等' => '@origin',
];
