<?php
/**
 * Generated By Command: translation:export
 */

return [
    '新增自定义维度' => '@origin',
    '维度名称' => '@origin',
    '您还能输入' => '@origin',
    '个字符，维度名称不能有中文' => '@origin',
    '取消' => '@origin',
    '确认' => '@origin',
    '字段不能为空' => '@origin',
    '请填写所需的字段' => '@origin',
    '不能为空' => '@origin',
    '维度名称不能为空' => '@origin',
];
