<?php
/**
 * Generated By Command: translation:export
 */

return [
    '全部文件' => '@origin',
    '全部图片' => '@origin',
    '全部文档' => '@origin',
    '选择文件' => '@origin',
    '图片' => '@origin',
    '文档' => '@origin',
    '上传本地文件' => '@origin',
    '取消' => '@origin',
    '确认' => '@origin',
    '提示' => '@origin',
    '部分上传失败' => '@origin',
    '搜索文件' => '@origin',
    '搜索' => '@origin',
    '全选' => '@origin',
    '加载中' => '@origin',
    '已全部加载' => '@origin',
    '全部' => '@origin',
    '文件夹' => '@origin',
    '新建文件夹' => '@origin',
    '已全部加载，共 :num 个' => '@origin',
    '已加载 :num 个' => '@origin',
    '已选择 :num 个' => '@origin',
    '上传完成, 共:num个文件' => '@origin',
    '你已经选中文件：' => '@origin',
    '文件格式仅限图片jpeg/jpg/png/gif 或者文档doc(x)/xls(x)/ppt(x)/pdf/txt' => '@origin',
    '单个图片文件大小不超过20M' => '@origin',
    '其他文件不能超过50M' => '@origin',
    '没有结果' => '@origin',
    '文件夹名称不能为空' => '@origin',
    '文件夹名称不能超过50字符' => '@origin',
    '文件夹名称只能包含数字、中英文、空格、（）- 或者 _' => '@origin',
    '文件夹名称只能以中英文或者数字开头' => '@origin',
    '其他' => '@origin'
];
