<?php
/**
 * Generated By Command: translation:export
 */

return [
    'Featured Stores' => '@origin',
    '销售增长趋势Top 10' => 'Top 10 Growing Products ',
    '最新降价产品' => 'Recent Price Drops ',
    '新入驻的店铺上架的新品(New Store Added)' => 'New Store Products',
    'Hot New/近3天内到货的新品' => 'Warehouse Arrival (within 3 days)',
    '精选新店铺(Select New Stores)' => 'Selected New Stores',
];
