<?php
/**
 * Generated By Command: translation:export
 */

return [
    '进行中' => '@origin',
    '待开启' => '@origin',
    '已结束' => '@origin',
    '当前活动不可编辑' => '@origin',
    '请输入活动名称' => '@origin',
    '活动名称不能超过200字' => '@origin',
    '开始时间不可早于当前时间' => '@origin',
    '开始时间必须要小于结束时间' => '@origin',
    '提交成功' => '@origin',
    '当前活动不可删除' => '@origin',
    '删除成功' => '@origin',
    '删除失败' => '@origin',
];
