<?php
/**
 * Generated By Command: translation:export
 */

return [
    '进行中' => '@origin',
    '待开启' => '@origin',
    '已结束' => '@origin',
    '已停止' => '@origin',
    '提交成功' => '@origin',
    '请输入活动名称' => '@origin',
    '活动名称不能超过200字' => '@origin',
    '开始时间不可早于当前时间' => '@origin',
    '开始时间必须要小于结束时间' => '@origin',
    '活动时间与已有活动时间冲突' => '@origin',
    '当前活动不可编辑' => '@origin',
    '交易方式错误' => '@origin',
    '请至少选择一个产品' => '@origin',
    '产品数量不可超过40个' => '@origin',
    '产品:skus已失效，请移除' => '@origin',
    '产品:skus活动库存超出当前上架库存，请重新设置' => '@origin',
    '操作失败，请重试' => '@origin',
    '操作成功' => '@origin',
    '操作失败，请重试2' => '操作失败，请重试',
    '暂无权限' => '@origin',
    '当前活动不存在' => '@origin',
    '补充活动库存失败' => '@origin',
    ':skus等产品库存不足，无法补充库存' => '@origin',
    ':skus产品库存不足，无法补充库存' => '@origin',
];
