<?php
/**
 * Generated By Command: translation:export
 */

return [
    '海运头程' => '@origin',
    '集装箱尺寸' => '@origin',
    '请选择集装箱尺寸' => '@origin',
    '起运港' => '@origin',
    '请选择起运港' => '@origin',
    '期望船期' => '@origin',
    '请选择期望船期' => '@origin',
    '预计到库时间' => '@origin',
    '请选择预计到库时间' => '@origin',
    '备注' => '@origin',
    '产品名称' => '@origin',
    '长' => '@origin',
    '宽' => '@origin',
    '高' => '@origin',
    '重量' => '@origin',
    '预计入库' => '@origin',
    '操作' => '@origin',
    '入库管理' => '@origin',
    '入库单明细' => '@origin',
    '预计入库数量' => '@origin',
];
