<?php
/**
 * 该文件定义已经翻译了的路由（即未在此配置中的路由不会进行中英文化翻译，默认为英文）
 * 注意需要包含 ajax 路由
 * @see ControllerStartupLang::needTrans()
 */

return [
    'catalog' => [
        // 完整路由地址 => 1(1无实际作用，仅为了保证 key 唯一，防止重复添加)
        'customerpartner/seller_center/index' => 1,
        'customerpartner/seller_center/recommend/detail' => 1,
        'customerpartner/product/lists/index' => 1,
        'customerpartner/product/lists/valid' => 1,
        'customerpartner/product/lists/invalid' => 1,
        'customerpartner/product/lists/audit' => 1,//审核记录列表
        'customerpartner/product/lists/soft_delete' => 1,//删除产品
        'customerpartner/product/lists/batch_recover' => 1,//恢复产品
        'customerpartner/product/lists/ltlWindow' => 1,
        'customerpartner/product/lists/ltlSave' => 1,
        'customerpartner/product/lists/ltlCancel' => 1,
        'customerpartner/product/lists/modify' => 1,
        'customerpartner/product/lists/onShelfProductAction' => 1,
        'customerpartner/product/lists/offShelfProductActionBeforeReminds' => 1,
        'customerpartner/product/lists/offShelfProductAction' => 1,
        'customerpartner/product/lists/auditCancel' => 1,
        'customerpartner/product/lists/getProductAuditInfo' => 1,
        'account/customerpartner/product_management/product/importProducts' => 1,
        'account/customerpartner/product_management/product/importProductsRecords' => 1,
        'account/customerpartner/product_management/product/importModifyProductsFile' => 1,
        'account/customerpartner/product_management/product/downloadImportProductsTemplate' => 1,
        'account/customerpartner/product_management/product/downloadModifyProductTemplate' => 1,
        'account/customerpartner/product_management/product/importProductsFile' => 1,
        'account/customerpartner/product_management/product/modifyPricesFile' => 1,
        'pro/product' => 1,
        'pro/product/storeProduct' => 1,
        'pro/product/checkRelationDelicacyProduct' => 1,
        'pro/product/checkMpnValid' => 1,
        'pro/freight' => 1,
        'pro/freight/index' => 1,
        'customerpartner/warehouse/receipt/importTemp' => 1,
        'customerpartner/warehouse/receipt/import' => 1,
        'account/print_product_labels' => 1,
        'customerpartner/warehouse/receipt' => 1,
        'customerpartner/warehouse/receipt/download' => 1,
        'customerpartner/warehouse/receipt/cancelReceiptOrder' => 1,
        'customerpartner/warehouse/receipt/add' => 1,
        'customerpartner/warehouse/batch_inventory' => 1,
        'customerpartner/warehouse/batch_inventory/downloadData' => 1,
        'customerpartner/warehouse/batch_inventory/getList' => 1,
        'customerpartner/warehouse/inout_inventory' => 1,
        'customerpartner/warehouse/inout_inventory/downloadData' => 1,
        'customerpartner/warehouse/inout_inventory/getList' => 1,
        'customerpartner/warehouse/inout_inventory/getInoutInventoryType' => 1,
        'customerpartner/warehouse/inventory_loss' => 1,
        'customerpartner/warehouse/inventory_loss/view' => 1,
        'customerpartner/warehouse/receipt/view' => 1,
        'customerpartner/warehouse/receipt/doAdd' => 1,
        'customerpartner/warehouse/receipt/doAddShipLaunch' => 1,
        'customerpartner/warehouse/receipt/doEdit' => 1,
        'customerpartner/warehouse/inventory_loss/getList' => 1,
        'account/seller_bill/bill' => 1,
        'account/seller_bill/bill/getTotalInfo' => 1,
        'account/seller_bill/bill/downloadPDF' => 1,
        'account/seller_bill/bill_list' => 1,
        'account/seller_bill/bill_list/getSettlementCycle' => 1,
        'account/seller_bill/bill_list/getSettlementList' => 1,
        'account/seller_bill/bill_list/getSettlementTrend' => 1,
        'account/seller_bill/bill_list/download' => 1,
        'account/seller_bill/bill_detail' => 1,
        'account/seller_bill/bill_detail/getSettlementType' => 1,
        'account/seller_bill/bill_detail/getList' => 1,
        'account/seller_bill/bill_detail/download' => 1,
        'account/seller_bill/bill_detail/downloadDetail' => 1,
        'account/product_quotes/margin_contract/view' => 1,
        'customerpartner/seller_store/home' => 1,
        'customerpartner/seller_store/home/initData' => 1,
        'customerpartner/seller_store/home/moduleSave' => 1,
        'customerpartner/seller_store/home/allSave' => 1,
        'customerpartner/seller_store/home/auditCancel' => 1,
        'customerpartner/seller_store/introduction' => 1,
        'customerpartner/seller_store/introduction/getStoreInfo' => 1,
        'customerpartner/seller_store/introduction/store' => 1,
        'customerpartner/seller_store/introduction/auditCancel' => 1,
        'account/phone/verify' => 1,
        'account/phone/change' => 1,
        'customerpartner/tripartite_agreement/detail' => 1,
        'account/file_manage/index' => 1,
        'account/file_manage/index/upload' => 1,
        'account/file_manage/index/makeDir' => 1,
        'account/file_manage/index/rename' => 1,
        'account/file_manage/index/move' => 1,
        'account/file_manage/index/delete' => 1,
        'customerpartner/marketing_campaign/discount/store' => 1,
        'customerpartner/marketing_campaign/discount/del' => 1,
        'customerpartner/marketing_campaign/time_limit_discount/store' => 1,
        'customerpartner/marketing_campaign/time_limit_discount/stop' => 1,
        'customerpartner/marketing_campaign/time_limit_discount/incrDiscountStockQty' => 1,
        'customerpartner/marketing_campaign/time_limit_discount/releaseDiscountStockQty' => 1,
        'customerpartner/marketing_campaign/index/activity' => 1,
        'customerpartner/marketing_campaign/discount_tab/index' => 1,
        'customerpartner/marketing_campaign/time_limit_discount/add' => 1,
        'customerpartner/marketing_campaign/time_limit_discount/editView' => 1,
        'customerpartner/marketing_campaign/discount/index' => 1,
        'customerpartner/marketing_campaign/time_limit_discount/index' => 1,
        'account/customerpartner/sidebar/price_calculator' => 1,
        'account/customerpartner/sidebar/price_calculator/getFee' => 1,
    ],
    'admin' => [
        //
    ],
];
