<?php
/**
 * Generated By Command: translation:export
 */

return [
    '是否确认发布?' => 'Do you confirm to publish the information?',
    '当前有已发布的信息待审核，是否继续发布并替换?' => 'There is already published information to be reviewed. Do you want to continue to publish this information and replace the published one?',
    '当前预览内容已修改，请刷新后重试！' => 'Modifications have been done to the current preview content. Please refresh the page and try again.',
    '发布成功，待平台审核！' => 'Publish successfully! Please wait for Marketplace review.',
    '未设置内容，是否删除并发布？' => ' have no content. Do you want to delete these two modules and publish the information?',
    '是否取消审核?' => 'Do you confirm to cancel the request for review?',
    '草稿箱中已有内容，是否将取消的内容保存至草稿箱，并替换已有内容?' => 'The content you canceled has been saved in the draft box before. Do you want to save the latest content after cancellation to replace the original content?',
    '是否将取消的内容保存至草稿箱?' => 'Do you want to save the latest content after cancellation?',
    '取消成功' => 'Canceled Successfully',
    '本次取消的内容将不会被保存' => 'The content canceled this time will not be saved',
    '确认' => 'Confirm',
    '您的申请已被驳回，请重新申请！' => 'Your request has been declined. Please submit a request again.',
    '驳回原因' => 'Reason for decline',
    '确定(yes)' => 'Yes',
    '取消(no)' => 'No',
    '全屏轮播' => 'Banner  Slideshow',
    '主推产品' => 'Featured Products',
    '产品推荐' => 'Recommend Products',
    '复杂交易' => 'Complex Transaction',
    '产品分类' => 'Product Category',
    '产品排名' => 'Sales Ranking',
    'Why Choose Us' => '@origin',
];
