<?php
/**
 * Generated By Command: translation:export
 */

return [
    'shipToPhone' => implode('|', [
        '{1} 電話番号',
        '{0} Phone',
    ]),
    'StreetAddress' => implode('|', [
        '{1} 番地,建物名,部屋番号',
        '{0} Shipping Address',
    ]),
    'ShipToPostalCode' => implode('|', [
        '{1} 郵便番号',
        '{0} Postal Code',
    ]),
    'ShipToCity' => implode('|', [
        '{1} 市区町村',
        '{0} City',
    ]),
    'ShipToState' => implode('|', [
        '{1} 都道府県',
        '{0} State',
    ]),
    'ShipToCountry' => implode('|', [
        '{1} 国',
        '{0} Country',
    ]),
];
