<?php
/**
 * Generated By Command: translation:export
 */

return [
    'Featured Stores' => '@origin',
    '销售增长趋势Top 10' => '@origin',
    '最新降价产品' => '@origin',
    '新入驻的店铺上架的新品(New Store Added)' => '@origin',
    'Hot New/近3天内到货的新品' => '@origin',
    '精选新店铺(Select New Stores)' => 'Selected New Stores',
];
