<?php
/**
 * Generated By Command: translation:export
 */

return [
    '敬爱的卖家，当产品尺寸符合以下任何条件时，FedEx（UPS）将生成Unauthorized Charge，这将导致$ :price /包裹的额外费用：' => '@origin',
    '最长边+周长＞ 165英寸' => '@origin',
    '或最长边> 108英寸' => '@origin',
    '或实际重量＞ 150磅' => '@origin',
    '平台会将满足以上尺寸的产品标记为LTL产品，并对这些产品收取LTL配送费用。' => '@origin',
    '根据平台的历史记录，总结了触发Unauthorized Charge风险的几率和相应的高风险产品特征：' => '@origin',
    '当153英寸<[最长边+周长]≤162英寸时，触发Unauthorized Charge风险的可能性小于3％。' => '@origin',
    '当[实际重量]> 148磅时，触发Unauthorized Charge风险的可能性大于10％。' => '@origin',
    '当[最长边]> 105英寸时，触发Unauthorized Charge风险的机会大于18％。' => '@origin',
    '当[最长边+周长]> 162英寸时，触发Unauthorized Charge风险的可能性大于50％。' => '@origin',
    '为了最大程度地减少损失，建议为较高触发风险的包裹选择LTL交付。如果您想使用LTL交付，请选中下面的确认框并单击“提交”以更改交付方式。' => '@origin',
    '由您决定是否使用零担交付。如果您确认不更改为LTL交付，则一旦发生Unauthorized Charge，平台会通过消息中心将这笔费用通知您，该费用将由您承担，并添加到您的最终账单中。任何产生的费用的通知将每周及时转发到您的消息中心。' => '@origin',
    'MPN' => '@origin',
    '长' => '@origin',
    '英寸' => '@origin',
    '宽' => '@origin',
    '高' => '@origin',
    '重' => '@origin',
    '磅' => '@origin',
    '最长边' => '@origin',
    '周长' => '@origin',
    '我确认为上述产品选择<span class="bold-weight">:type</span>配送' => '@origin',
    '快递' => '@origin',
    'LTL' => '@origin',
];
