<?php
/**
 * Generated By Command: translation:export
 */

return [
    'MPN必须大于4且小于30个字符。' => '@origin',
    '失败！MPN不能重复。' => '@origin',
    '产品标题必须大于1且小于200个字符。' => '@origin',
    '产品尺寸必须大于0且小于80个字符。' => '@origin',
    '可单独售卖的产品必须设置主图。' => '@origin',
    '产品标题不能为空。' => '@origin',
    '文档素材为必填项。' => '@origin',
    '主要颜色不能为空。' => '@origin',
    '主要材质不能为空。' => '@origin',
    '仅能输入英文和数字' => '@origin',
    '失败！MPN不能与已存在的Item Code重复。' => '@origin',
];
