<?php
/**
 * Generated By Command: translation:export
 */

return [
    '批量导入模板.xlsx' => '@origin',
    '批量修改模板.xlsx' => '@origin',
    '从Category ID sheet表中选择类目，输入对应的CategoryID' => '@origin',
    '从Platform Names sheet表中选择不可售卖的平台，如果有多个用[|]隔开' => '@origin',
    '专利产品选择是时，专利证书必填。请填入文件管理中的图片路径，如果有多张图片用[|]隔开,最多支持9张' => '@origin',
    '仅支持输入文字描述' => '@origin',
    '请填入文件管理中的图片路径，限一张图片' => '@origin',
    '请填入文件管理中的图片路径，如果有多张图片用[|]隔开,最多支持26张' => '@origin',
    '请填入文件管理中的图片路径，如果有多张图片用[|]隔开,最多支持27张' => '@origin',
    '请填入文件管理中的图片/文档路径，如果有多个图片/文档用[|]隔开,最多支持27个文件' => '@origin',
    '请填入文件管理中的txt文档路径，如果有多个文档用[|]隔开,最多支持27个文件' => '@origin',
    '产品尺寸
输入 0.01 到 999.99 之间的数字或输入“Not Applicable”' => '@origin',
    '产品包装信息' => '@origin',
    '产品是否能单独售卖
    注意：输入“No”会导致产品不在前台页面显示，buyer看不到该产品' => '@origin',
    '该产品是否支持定制' => '@origin',
    '原产地国家/地区' => '@origin',
    '选择填充物/内部材料' => '@origin',

    'Visible = 所有买家都可以查看价格和数量Invisible =在买方要求与卖方建立联系之前无法查看价格和数量' => '@origin',
    '该产品是否获得专利或版权？' => '@origin',

    'General item=可自行出售的物品；组合商品中的组成
Combo item = 多个商品组成，由1个以上的商品组成
Replacement part =替换件，不能单独出售' =>'@origin'


];
