<?php
/**
 * Generated By Command: translation:export
 */

return [
    '文件夹移动失败，目前只支持3层文件目录' => '@origin',
    '文件夹名称不规范' => '@origin',
    '上传文件不合法' => '@origin',
    '单个图片文件大小不超过20M，其他文件不能超过50M' => '@origin',
    '文件格式仅限图片jpeg/jpg/png/gif 或者文档doc(x)/xls(x)/ppt(x)/pdf/txt' => '@origin',
    '同一文件夹下，文件名称不能重复' => '@origin',
    '文件夹名称不能重复' => '@origin',
    '文件名称不规范' => '@origin',
    '文件重命名成功' => '@origin',
    '文件移动成功' => '@origin',
    '文件删除成功' => '@origin',
    '不能将文件夹移动到自身或者其子目录下' => '@origin',
    '部分文件已存在,移动失败' => '@origin',
    '文件名称只能包含数字、中英文、空格、（）- 或者 _' => '@origin',
    '文件名称不能超过100字符' => '@origin',
    '文件名称只能以中英文或者数字开头' => '@origin',
    '文件不存在' => '@origin',
];
