<?php
/**
 * Generated By Command: translation:export
 */

return [
    '无效入库类型' => '@origin',
    '无效筛选时间' => '@origin',
    '系统繁忙，请稍后在试' => '@origin',
    'No.' => '@origin',
    'Item Code' => '@origin',
    'MPN' => '@origin',
    '产品名称' => '@origin',
    '入库类型' => '@origin',
    '仓库收货数量' => '@origin',
    '当前在库数' => '@origin',
    '入库天数' => '@origin',
    '批次号' => '@origin',
    '备注' => '@origin',
    '批次生成日期' => '@origin',
    '入库日期' => '@origin',
    '无效的入出库分类' => '@origin',
    '无效的入出库类型' => '@origin',
    '入库' => '@origin',
    '出库' => '@origin',
    '无效的筛选时间' => '@origin',
    '无效的入库类型' => '@origin',
    '入库/出库' => '@origin',
    '类型' => '@origin',
    '数量' => '@origin',
    '生成日期' => '@origin',
    '提交成功' => '@origin',
    '生成日期_1' => '生成日期',
];
