<?php
/**
 * Generated By Command: translation:export
 */

return [
    '请输入站内链接！' => '@origin',
    '所选产品:sku，未在:category分类中，请移除这些产品！' => '@origin',
    '产品:sku已失效，请移除这些产品！' => '@origin',
    '产品:sku返点合约已失效，请移除这些产品！' => '@origin',
    '产品:sku期货合约已失效，请移除这些产品！' => '@origin',
    '产品:sku现货合约已失效，请移除这些产品！' => '@origin',
    '产品:sku已下架，请移除这些产品！' => '@origin',
    '这个当前页面无模块，请先添加模块' => '@origin',
];
