<?php
/**
 * Generated By Command: translation:export
 */

return [
    '新增自定义维度' => 'Add a Custom Field',
    '维度名称' => 'Field Name',
    '您还能输入' => 'You can enter',
    '个字符，维度名称不能有中文' => 'characters, please do not enter Chinese in the field name.',
    '取消' => 'Cancel',
    '确认' => 'Submit',
    '字段不能为空' => 'can not be blank.',
    '请填写所需的字段' => 'Please complete the required field',
    '不能为空' => ' can not be blank',
    '维度名称不能为空' => 'Field Name can not be blank',
];
