<?php
/**
 * Generated By Command: translation:export
 */

return [
    '全部文件' => 'All Files',
    '全部图片' => 'All Images',
    '全部文档' => 'All Documents',
    '选择文件' => 'Select Files to Upload',
    '图片' => 'Images',
    '文档' => 'Documents',
    '上传本地文件' => 'Upload',
    '取消' => 'Cancel',
    '确认' => 'Confirm',
    '提示' => 'Attention',
    '部分上传失败' => 'Part of the files are failed to be uploaded',
    '搜索文件' => 'Search',
    '搜索' => 'Search',
    '全选' => 'Select All',
    '加载中' => 'Loading',
    '已全部加载' => 'All files have been loaded',
    '全部' => 'All',
    '文件夹' => 'Folders',
    '新建文件夹' => 'New folders',
    '已全部加载，共 :num 个' => 'All files have been loaded, :num in total',
    '已加载 :num 个' => ':num files already loaded',
    '已选择 :num 个' => ':num file(s) selected',
    '上传完成, 共:num个文件' => 'Uploading completed, :num files in total',
    '你已经选中文件：' => 'You have already chosen:',
    '文件格式仅限图片jpeg/jpg/png/gif 或者文档doc(x)/xls(x)/ppt(x)/pdf/txt' => 'The file only supports images in .jpeg/.jpg/.png/.gif format or documents in .doc(x)/.xl(s)/.ppt(x)/.txt format.',
    '单个图片文件大小不超过20M' => 'The single image size should not be larger than 20M.',
    '其他文件不能超过50M' => 'The other files not larger than 50M.',
    '没有结果' => 'No data was found.',
    '文件夹名称不能超过50字符' => 'The folder name shall be limited to 50 characters.',
    '文件夹名称不能为空' => 'The folder name cannot be empty.',
    '文件夹名称只能包含数字、中英文、空格、（）- 或者 _' => 'The folder name can only contain digits, Chinese characters, English letters, spaces, \'( )\', \'-\' or \'_\'.',
    '文件夹名称只能以中英文或者数字开头' => 'The folder name can only start with a Chinese characters, English letters or a digit.',
    '其他' => 'Other',
    '暂无其他文件，' => 'No other documents.'

];
