<?php
/**
 * Generated By Command: translation:export
 */

return [
    '对公账户' => 'Corporate Account',
    '对私账户' => 'Private Account',
    'P卡' => 'Payoneer',
    '正在进行' => 'In Progress',
    '结算中' => 'In Settlement',
    '已结算' => 'Settled',
    '已结算（转期初金额）' => 'Settled (Transfer to Beginning Balance)',
    '未知状态' => 'Unknown Status',
    '无需冻结' => '',
    '冻结中' => 'Under Review',
    '已解冻' => 'Available ',
];
