<?php
/**
 * Generated By Command: translation:export
 */

return [
    '产品质量' => 'Product Quality',
    '交易稳定' => 'Transaction Reputation',
    '服务质量' => 'Customer Service',
    '商家信誉' => 'Store Credibility',
];
