<?php
/**
 * Generated By Command: translation:export
 */

return [
    '自动推荐' => 'Auto-Recommendation',
    '手工添加' => 'Manually Adding',
    '热卖产品在前' => 'Best selling products rank first',
    '新品到货在前' => 'New arrivals rank first',
    '热门下载在前' => 'Hot products rank first',
    '价格最低在前' => 'Products with lowest price rank first',
    '价格最低在后' => 'Products with lowest price rank last',
];
