<?php
/**
 * Generated By Command: translation:export
 */

return [
    '资产管理' => '@origin',
    '总资产计算' => '总资产=供应链金融+预计应收款+在库抵押物+在途抵押物+抵押物支付期货保证金+人民币押金/汇率+资产调整金额',
    '总资产' => '@origin',
    '供应链金融' => '@origin',
    '抵押物支付期货保证金' => '@origin',
    '预计应付款' => '@origin',
    '在库抵押物' => '@origin',
    '在途抵押物' => '@origin',
    '人民币押金' => '@origin',
    '资产调整金额' => '@origin',
    '纯物流预计费用' => '@origin',
    '抵押物预计减值金额' => '@origin',
];
