<?php
/**
 * Generated By Command: translation:export
 */

return [
    '修改手机号' => '@origin',
    '验证手机号' => '@origin',
    '完成' => '@origin',
    '手机号码' => '@origin',
    '验证码' => '@origin',
    '点此获取' => '@origin',
    '没有收到短信验证码？' => '@origin',
    '1、网络通讯异常可能会造成短信丢失，请重新获取或稍后再试。' => '@origin',
    '2、请核实手机是否已欠费停机，或者屏蔽了系统短信。' => '@origin',
    '3、您也可以尝试将SIM卡移动到另一部手机，然后重试。' => '@origin',
    '确定' => '@origin',
    '添加成功，您的手机号码为' => '@origin',
    '此手机号可作为安全验证的方式用于找回密码、修改手机号等场景，但不能作为登录名使用。' => '@origin',
    '账号设置' => '@origin',
    '验证码已发送到你的手机，5分钟内输入有效，请不要轻易告知他人' => '@origin',
    '手机号码是11位数字，请重新输入' => '@origin',
    '修改成功，您的手机号码为<span id="savedNumber"></span>' => '@origin',
    '<span id="returnTime">3</span>s后返回<a class="link underline" id="redirect-home" href=":url">:page</a>' => '@origin',
    'Seller Central页面' => '@origin',
    '首页' => '@origin',
    '添加成功，您的手机号码为<span id="savedNumber"></span>' => '@origin',
    '验证手机号step' => '验证手机号',
    '修改手机号step' => '修改手机号',
    '手机验证码验证账户 <span class="text-danger">:email</span>，为确认是你本人操作，请完成以下验证' => '@origin',
    '国家/ 编码' => '@origin',
];
