#!/bin/sh
#set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi
ps -ef|grep "supervisord"|grep -v grep
if [ $? -ne 0 ]; then
    /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
fi
exec "$@"
