<?php
/**
 * Generated By Command: translation:export
 */

return [
    '修改' => '@origin',
    '取消审核' => '@origin',
    '图片介绍' => '@origin',
    '最多可上传:num张，建议上传产品或生产图片，图片要求宽度:width，高度:height，格式为:ext。' => '@origin',
    '店铺介绍' => '@origin',
    '请输入' => '@origin',
    '主营品类' => '@origin',
    '联系邮箱' => '@origin',
    '联系电话' => '@origin',
    '微信二维码' => '@origin',
    '超出最大上传张数' => '@origin',
    '是否取消审核' => '@origin',
    '确认' => '@origin',
    '取消成功' => '@origin',
    '请上传图片' => '@origin',
    '请输入:field' => '@origin',
    '请输入正确的邮箱' => '@origin',
    '仅允许输入:from-:to位数字' => '@origin',
    '发布' => '@origin',
    '正在审核中' => '@origin',
    '已发布' => '@origin',
    '已驳回' => '@origin',
    '最多选择:num项，以选择先后顺序展示' => '@origin',
    '确定(yes)' => '确定',
    '取消(no)' => '取消',
    '请输入介绍文案，:num字以内' => '@origin',
    '预览' => '@origin',
    '去发布' => '发布',
];
