<?php
/**
 * Generated By Command: translation:export
 */

return [
    '资产管理' => 'Assets Management',
    '总资产' => 'Total Assets',
    '供应链金融' => 'Supply Chain Finance',
    '预计应付款' => 'Estimated Receivables',
    '在库抵押物' => 'Collateral in Stock',
    '在途抵押物' => 'Collateral in Transit',
    '人民币押金' => 'Deposit in RMB',
    '资产调整金额' => 'Asset Adjustment Amount',
    '抵押物支付期货保证金' => 'Collateral for Futures Deposit',
    '纯物流预计费用' => 'Estimated Cost for Logistics Order',
    '总资产计算' => 'Total Assets = Supply Chain Finance + Estimated Receivables + Collateral in Stock + Collateral in Transit + Collateral for Futures Deposit + Deposit in RMB/Exchange Rate + Asset Adjustment Amount',
    '抵押物预计减值金额' => 'Estimated Deducted Value from Collateral',
];
