<?php
/**
 * Generated By Command: translation:export
 */

return [
    '上传文件中的upload Id为非法数据' => '@origin',
    '云送仓导单无此产品信息' => '@origin',
    'Line :row :云送仓批量导单校验体积失败' => '@origin',
    ':recipient,:phone,:address :原云送仓尺寸报错提醒' => '@origin',
    'Line :row :平台无可购买的库存数量，请检查下您的需求是否可调整' => '@origin',
];
