<?php
/**
 * Generated By Command: translation:export
 */

return [
    'wayfair上传label是否可以识别运单号' => 'The tracking number in this shipping label cannot be recognized. Please upload again.',
    '不允许上传多页的商业发票。请重新上传' => 'Commercial invoices with more than one page are not allowed. Please upload again.',
];
