<?php
/**
 * Generated By Command: translation:export
 */

return [
    '第:line行，MPN不能为空！' => '@origin',
    '第:line行，更新价格不能为空！' => '@origin',
    '第:line行，更新价格格式不正确！' => '@origin',
    '第:line行，MPN与相应产品不匹配！' => '@origin',
    '第:line行，生效时间不能为空！' => '@origin',
    '第:line行，生效时间格式不正确！' => '@origin',
    '第:line行，生效时间必须晚于当前时间24小时以上！' => '@origin',
    '第:line行，更新价格只能在:min到:max之间！' => '@origin',
    '第:line行，生效时间不能早于当前时间！' => '@origin',
];
