<?php
/**
 * Generated By Command: translation:export
 */

return [
    '批量导入模板.xlsx' => 'Template - Batch Upload.xlsx',
    '批量修改模板.xlsx' => 'Template - Batch Modify.xlsx',
    '从Category ID sheet表中选择类目，输入对应的CategoryID' => "Find the corresponding Category ID on the 'Category ID Sheet' and enter it.",
    '从Platform Names sheet表中选择不可售卖的平台，如果有多个用[|]隔开' => "Enter the corresponding platform names according to the 'Platform Names sheet'. Use '|' to seperate multiple platform names.",
    '专利产品选择是时，专利证书必填。请填入文件管理中的图片路径，如果有多张图片用[|]隔开,最多支持9张' => "If 'Yes' is selected for 'Original Design', this field is required. Enter the image path under the 'File Management' menu and use '|' to separate multiple images. A miximum of 9 images are permitted for Supporting Files.",
    '仅支持输入文字描述' => 'Only a text description is permitted.',
    '请填入文件管理中的图片路径，限一张图片' => "Enter the main image path under the 'File Management' menu. One main image is permitted.",
    '请填入文件管理中的图片路径，如果有多张图片用[|]隔开,最多支持26张' => "Enter the image path under the 'File Management' menu and use '|' to separate multiple images. A maximum of 26 images are permitted.",
    '请填入文件管理中的图片路径，如果有多张图片用[|]隔开,最多支持27张' => "Enter the image path under the 'File Management' menu and use '|' to separate multiple images. A maximum of 27 images are permitted.",
    '请填入文件管理中的图片/文档路径，如果有多个图片/文档用[|]隔开,最多支持27个文件' => "Enter the image/document path under the 'File Management' menu and use '|' to separate multiple images/documents. A maximum of 27 images/documents are permitted.",
    '请填入文件管理中的txt文档路径，如果有多个文档用[|]隔开,最多支持27个文件' => "Enter the document paths in .txt format under the 'File Management' menu and use '|' to separate multiple documents. A maximum of 27 documents are permitted.",

    '产品尺寸
输入 0.01 到 999.99 之间的数字或输入“Not Applicable”' => 'Product Dimensions

Enter a number 0.01 to 999.99 or put `Not Applicable`',

    '产品包装信息' => 'Package Details',
    '产品是否能单独售卖
    注意：输入“No”会导致产品不在前台页面显示，buyer看不到该产品' => 'Should this product be sold by itself?

    NOTE: Putting a NO will result in the item not showing on the interface.  The product would not be seen by buyers',
    '该产品是否支持定制' => 'Is this product customizable?',
    '原产地国家/地区' => 'Country of Origin',
    '选择填充物/内部材料' => 'List any stuffed/interior material',
    'Visible = 所有买家都可以查看价格和数量Invisible =在买方要求与卖方建立联系之前无法查看价格和数量' => 'Visible = Price & Quantity can be viewed by all buyers
Invisible = Price & Qty cannot be viewed until Buyer requests affiliation with Seller',
    '该产品是否获得专利或版权？' => 'Is this product patented or copyrighted?',

    'General item=可自行出售的物品；组合商品中的组成
Combo item = 多个商品组成，由1个以上的商品组成
Replacement part =替换件，不能单独出售' => 'General item = items that can be sold by itself; Individual boxes for Combo Items
Combo item = items in a set;  combined by more than 1 packages
Replacement part = items that cannot be sold by itself'
];
