<?php
/**
 * Generated By Command: translation:export
 */

return [
    '修改' => 'Modified',
    '取消审核' => 'Cancel the request (for review)',
    '图片介绍' => 'Image Intro',
    '最多可上传:num张，建议上传产品或生产图片，图片要求宽度:width，高度:height，格式为:ext。' => 'A maximum of :num images can be uploaded, including product or production images.Size limit: Images with width of :width and height of :height, in :ext format only.',
    '店铺介绍' => 'Store Intro',
    '请输入' => 'Please enter',
    '主营品类' => 'Main Category',
    '联系邮箱' => 'Email',
    '联系电话' => 'Contact Number',
    '微信二维码' => 'Wechat QR Code',
    '是否取消审核' => 'Do you confirm to cancel the request for review?',
    '确认' => 'Confirm',
    '取消成功' => 'Canceled Successfully',
    '超出最大上传张数' => 'Exceed the maximum limit for allowed numbers of images',
    '请上传图片' => 'Upload images',
    '请输入:field' => 'Please Enter :field',
    '请输入正确的邮箱' => 'Enter a valid email address',
    '仅允许输入:from-:to位数字' => 'Enter :from-:to digits',
    '发布' => 'published',
    '正在审核中' => 'Under Review',
    '已发布' => 'Published',
    '已驳回' => 'Declined',
    '最多选择:num项，以选择先后顺序展示' => 'A maximum of :num categories can be selected, and these will be displayed in the order of selection',
    '确定(yes)' => 'Yes',
    '取消(no)' => 'No',
    '请输入介绍文案，:num字以内' => 'Enter the introduction text within :num characters',
    '预览' => 'Preview',
    '去发布' => 'Publish',
];
