<?php
/**
 * Generated By Command: translation:export
 */

return [
    '个人中心' => 'Seller Central',
    '主页' => 'Home',
    '我的店铺' => 'My Store',
    '帮助中心' => 'Help Center',
    '计算器' => 'Calculator',
    '账户设置' => 'Account Settings',
    '退出' => 'Logout',
];
