<?php
/**
 * Generated By Command: translation:export
 */

return [
    '文件不能上传！' => 'File could not be uploaded!',
    '错误的文件格式！' => 'Invalid file type!',
    '上传的Excel文件内容不正确或数据行为空。' => 'The content of the uploaded Excel file is incorrect or data row is empty.',
    '文件为空，请重新上传！' => 'The file is empty, please upload again!',
    'error_upload_code' => implode('|', [
        'Unknown Error :count',
        '{1} Warning: The uploaded file exceeds the upload_max_filesize directive in php.ini!',
        '{2} Warning: The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form!',
        '{3} Warning: The uploaded file was only partially uploaded!',
        '{4} Warning: No file was uploaded!',
        '{6} Warning: Missing a temporary folder!',
        '{7} Warning: Failed to write file to disk!',
        '{8} Warning: File upload stopped by extension!',
        '{999} Warning: No error code available!',
    ]),
    '文件名' => 'file name',
];
