<?php
/**
 * Generated By Command: translation:export
 */

return [
    '敬爱的卖家，当产品尺寸符合以下任何条件时，FedEx（UPS）将生成Unauthorized Charge，这将导致$ :price /包裹的额外费用：' => 'Dear seller, when the product size meets any of the following conditions, an Unauthorized Charge will be generated from FedEx(UPS), which will result in an additional fee of $:price/ package:',
    '最长边+周长＞ 165英寸' => 'Longest Side + Girth ＞ 165 inches',
    '或最长边> 108英寸' => 'or Longest Side ＞ 108 inches',
    '或实际重量＞ 150磅' => 'or Actual Weight ＞ 150 lbs',
    '平台会将满足以上尺寸的产品标记为LTL产品，并对这些产品收取LTL配送费用。' => 'The Marketplace will flag products that meet the above dimensions as LTL products and apply LTL charge rate to these products.',
    '根据平台的历史记录，总结了触发Unauthorized Charge风险的几率和相应的高风险产品特征：' => 'Based on historical order records of the Marketplace, the chance of triggering Unauthorized Risk and the corresponding high-risk product characteristics are summarized below:',
    '当153英寸<[最长边+周长]≤162英寸时，触发Unauthorized Charge风险的可能性小于3％。' => 'When 153 inches <[Longest side + Girth] ≤ 162 inches, the chance of triggering Unauthorized Risk is less than 3%.',
    '当[实际重量]> 148磅时，触发Unauthorized Charge风险的可能性大于10％。' => 'When [Actual weight]> 148 lbs, the chance of triggering Unauthorized Risk is greater than 10%.',
    '当[最长边]> 105英寸时，触发Unauthorized Charge风险的机会大于18％。' => 'When [Longest side]> 105 inches, the chance of triggering Unauthorized Risk is greater than 18%.',
    '当[最长边+周长]> 162英寸时，触发Unauthorized Charge风险的可能性大于50％。' => 'When [Longest side + Girth]> 162 inches, the chance of triggering Unauthorized Risk is greater than 50%.',
    '为了最大程度地减少损失，建议为较高触发风险的包裹选择LTL交付。如果您想使用LTL交付，请选中下面的确认框并单击“提交”以更改交付方式。' => 'In order to minimize losses, it is recommended to select LTL delivery for packages that have an increased chance of triggering Unauthorized Risk. If you would like to use LTL delivery, please check the box below and click on ‘Submit’ to change your delivery method.',
    '由您决定是否使用零担交付。如果您确认不更改为LTL交付，则一旦发生Unauthorized Charge，平台会通过消息中心将这笔费用通知您，该费用将由您承担，并添加到您的最终账单中。任何产生的费用的通知将每周及时转发到您的消息中心。' => 'It’s up to you to decide whether to use LTL delivery or not. If you confirm not to change to LTL delivery, once Unauthorized Charge is occurred, the Marketplace will notify you of this fee via Message Center. The fee will be borne by you and added to your final Marketplace bill. Notifications of any incurred fees will be promptly forwarded to your Message Center on a weekly basis.',
    'MPN' => '@origin',
    '长' => 'Length',
    '英寸' => 'inches',
    '宽' => 'Width',
    '高' => 'Height',
    '重' => 'Weight',
    '磅' => 'lbs',
    '最长边' => 'Longest side',
    '周长' => 'Girth',
    '我确认为上述产品选择<span class="bold-weight">:type</span>配送' => 'I confirm to use&nbsp;<span class="bold-weight">:type</span>&nbsp;for above product',
    '快递' => 'Parcel Carrier',
    'LTL' => 'LTL delivery',
];
