<?php
/**
 * Generated By Command: translation:export
 */

return [
    '是否确认发布?' => '@origin',
    '当前有已发布的信息待审核，是否继续发布并替换?' => '@origin',
    '当前预览内容已修改，请刷新后重试！' => '@origin',
    '发布成功，待平台审核！' => '@origin',
    '未设置内容，是否删除并发布？' => '@origin',
    '是否取消审核?' => '@origin',
    '草稿箱中已有内容，是否将取消的内容保存至草稿箱，并替换已有内容?' => '@origin',
    '是否将取消的内容保存至草稿箱?' => '@origin',
    '取消成功' => '@origin',
    '本次取消的内容将不会被保存' => '@origin',
    '确认' => '@origin',
    '您的申请已被驳回，请重新申请！' => '@origin',
    '驳回原因' => '@origin',
    '确定(yes)' => '确定',
    '取消(no)' => '取消',
    '全屏轮播' => '@origin',
    '主推产品' => '@origin',
    '产品推荐' => '@origin',
    '复杂交易' => '@origin',
    '产品分类' => '@origin',
    '产品排名' => '@origin',
    'Why Choose Us' => '@origin',
];
